#pragma once

#include "EInputDevice.h"

namespace tabi
{
    enum class EKeyboard
    {
        // Letters
        A = 1 | static_cast<unsigned>(EInputDevice::Keyboard),
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        // Modifiers
        LCTRL,
        CTRL = LCTRL,
        RCTRL,
        LALT,
        ALT = LALT,
        ALT_GR,
        RALT = ALT_GR,
        LSHIFT,
        SHIFT = LSHIFT,
        RSHIFT,
        ENTER,
        RETURN = ENTER,
        BACKSPACE,
        ESCAPE,
        ESC = ESCAPE,
        SPACE,
        TAB,
        // Arrows
        ARROW_UP,
        ARROW_DOWN,
        ARROW_LEFT,
        ARROW_RIGHT,
        // Numbers
        KEY0,
        KEY1,
        KEY2,
        KEY3,
        KEY4,
        KEY5,
        KEY6,
        KEY7,
        KEY8,
        KEY9,
        // Numpad/Keypad
        KP_0,
        KP_INSERT = KP_0,
        KP_1,
        KP_END = KP_1,
        KP_2,
        KP_DOWN = KP_2,
        KP_3,
        KP_PGDOWN = KP_3,
        KP_4,
        KP_LEFT = KP_4,
        KP_5,
        KP_BEGIN = KP_5,
        KP_6,
        KP_RIGHT = KP_6,
        KP_7,
        KP_HOME = KP_7,
        KP_8,
        KP_UP = KP_8,
        KP_9,
        KP_PGUP = KP_9,
        KP_PLUS,
        KP_ADD = KP_PLUS,
        KP_MINUS,
        KP_SUBTRACT = KP_MINUS,
        KP_SLASH,
        KP_DIVIDE = KP_SLASH,
        KP_ASTERISK,
        KP_MULTIPLY = KP_ASTERISK,
        KP_DOT,
        KP_DELETE = KP_DOT,
        KP_ENTER,
        // Function keys
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
    };
}